// frontend/src/components/FilePanel.tsx
import React, { useState, useRef, useEffect } from 'react';
import { useFiles } from '../context/FileContext';
import './FilePanel.css';

interface FilePanelProps {
  conversationId: number;
}

const FilePanel: React.FC<FilePanelProps> = ({ conversationId }) => {
  const {
    files,
    currentFile,
    isFilePanelOpen,
    setFilePanelOpen,
    loadFile,
    deleteFile,
    createNewFile,
  } = useFiles();

  const [isCreatingFile, setIsCreatingFile] = useState(false);
  const [newFileName, setNewFileName] = useState('');
  const panelRef = useRef<HTMLDivElement>(null);

  const handleFileClick = async (filename: string) => {
    if (filename !== currentFile) {
      await loadFile(conversationId, filename);
    }
    setFilePanelOpen(false);
  };

  const handleCreateFile = async () => {
    if (newFileName.trim() && !files.includes(newFileName.trim())) {
      let filename = newFileName.trim();
      if (!filename.endsWith('.py')) {
        filename += '.py';
      }
      
      try {
        await createNewFile(conversationId, filename);
        setNewFileName('');
        setIsCreatingFile(false);
      } catch (error) {
        alert('Failed to create file');
      }
    }
  };

  const handleDeleteFile = async (filename: string, event: React.MouseEvent) => {
    event.stopPropagation();
    
    if (filename === 'runner.py') {
      alert('Cannot delete runner.py');
      return;
    }

    if (window.confirm(`Delete ${filename}?`)) {
      try {
        await deleteFile(conversationId, filename);
      } catch (error) {
        alert('Failed to delete file');
      }
    }
  };

  const togglePanel = () => {
    setFilePanelOpen(!isFilePanelOpen);
  };

  // Handle clicking outside the panel to close it
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (isFilePanelOpen && panelRef.current && !panelRef.current.contains(event.target as Node)) {
        setFilePanelOpen(false);
      }
    };

    if (isFilePanelOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isFilePanelOpen, setFilePanelOpen]);

  return (
    <div className="file-panel" ref={panelRef}>
      {/* File Icon Button */}
      <button
        className="file-panel__toggle-btn"
        onClick={togglePanel}
        aria-label="Toggle file panel"
        title="Files"
      >
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M3 3h7l2 2h9v14H3V3z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      </button>

      {/* File Panel */}
      {isFilePanelOpen && (
        <div className="file-panel__overlay">
          <div className="file-panel__content">
            <div className="file-panel__header">
              <h3>Files</h3>
              <div className="file-panel__actions">
                <button
                  className="file-panel__action-btn"
                  onClick={() => setIsCreatingFile(true)}
                  title="New File"
                >
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12 5v14M5 12h14" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </button>
                <button
                  className="file-panel__action-btn"
                  onClick={() => setFilePanelOpen(false)}
                  title="Close"
                >
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </button>
              </div>
            </div>

            {/* New File Input */}
            {isCreatingFile && (
              <div className="file-panel__new-file">
                <input
                  type="text"
                  value={newFileName}
                  onChange={(e) => setNewFileName(e.target.value)}
                  placeholder="filename.py"
                  className="file-panel__new-file-input"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      handleCreateFile();
                    } else if (e.key === 'Escape') {
                      setIsCreatingFile(false);
                      setNewFileName('');
                    }
                  }}
                  autoFocus
                />
                <div className="file-panel__new-file-actions">
                  <button
                    className="file-panel__new-file-btn file-panel__new-file-btn--create"
                    onClick={handleCreateFile}
                  >
                    Create
                  </button>
                  <button
                    className="file-panel__new-file-btn file-panel__new-file-btn--cancel"
                    onClick={() => {
                      setIsCreatingFile(false);
                      setNewFileName('');
                    }}
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}

            {/* File List */}
            <div className="file-panel__files">
              {files.length === 0 ? (
                <div className="file-panel__empty">No files</div>
              ) : (
                files.map((filename) => (
                  <div
                    key={filename}
                    className={`file-panel__file ${
                      filename === currentFile ? 'file-panel__file--active' : ''
                    }`}
                    onClick={() => handleFileClick(filename)}
                  >
                    <div className="file-panel__file-icon">
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                        <path d="M14 2v6h6M16 13H8M16 17H8M10 9H8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    </div>
                    <span className="file-panel__file-name">{filename}</span>
                    {filename !== 'runner.py' && (
                      <button
                        className="file-panel__file-delete"
                        onClick={(e) => handleDeleteFile(filename, e)}
                        title="Delete file"
                      >
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                      </button>
                    )}
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default FilePanel;

// codespace-app/src/components/FilePanel.vue
<template>
  <div class="file-panel">
    <button
      class="file-panel__toggle"
      @click="isOpen = !isOpen"
      :title="isOpen ? 'Close file panel' : 'Open file panel'"
    >
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
      <span v-if="!isOpen">Files</span>
    </button>

    <div v-if="isOpen" class="file-panel__dropdown">
      <div class="file-panel__header">
        <h3>Files</h3>
        <button @click="handleCreateFile" class="file-panel__create-btn" title="Create new file">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
          </svg>
        </button>
      </div>
      <div class="file-panel__list">
        <div
          v-for="file in files"
          :key="file"
          :class="['file-panel__item', { 'file-panel__item--active': file === currentFile }]"
          @click="handleFileClick(file)"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M13 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V9l-7-7z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M13 2v7h7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          <span class="file-panel__filename">{{ file }}</span>
          <button
            v-if="file !== 'runner.py'"
            @click.stop="handleDeleteFile(file)"
            class="file-panel__delete-btn"
            title="Delete file"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, watch } from 'vue';
import { useFile } from '../composables/useFile';
import { voiceService } from '../services/voiceService';

export default {
  name: 'FilePanel',
  props: {
    conversationId: {
      type: Number,
      required: true
    }
  },
  setup(props) {
    const { files, currentFile, loadFiles, loadFile, deleteFile } = useFile();
    const isOpen = ref(false);

    watch(() => props.conversationId, async (newId) => {
      if (newId) {
        await loadFiles(newId);
      }
    }, { immediate: true });

    const handleFileClick = async (filename) => {
      try {
        await loadFile(props.conversationId, filename);
        isOpen.value = false;
      } catch (err) {
        console.error('Failed to load file:', err);
      }
    };

    const handleCreateFile = async () => {
      const filename = prompt('Enter new file name (e.g., my_module.py):');
      if (!filename) return;

      if (!filename.endsWith('.py')) {
        alert('File must have .py extension');
        return;
      }

      if (files.value.includes(filename)) {
        alert('File already exists');
        return;
      }

      try {
        const { saveFile } = useFile();
        await saveFile(props.conversationId, filename, '');
        await loadFiles(props.conversationId);
        await loadFile(props.conversationId, filename);
        voiceService.speak('File created successfully');
      } catch (err) {
        console.error('Failed to create file:', err);
        voiceService.speak('Failed to create file');
      }
    };

    const handleDeleteFile = async (filename) => {
      if (!confirm(`Delete ${filename}?`)) return;

      try {
        await deleteFile(props.conversationId, filename);
        voiceService.speak('File deleted successfully');
      } catch (err) {
        console.error('Failed to delete file:', err);
        voiceService.speak('Failed to delete file');
      }
    };

    return {
      isOpen,
      files,
      currentFile,
      handleFileClick,
      handleCreateFile,
      handleDeleteFile,
    };
  }
};
</script>

<style scoped>
.file-panel {
  position: relative;
  margin-right: 1rem;
}

.file-panel__toggle {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  background: var(--primary-color, #001f3f);
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: background 0.2s;
}

.file-panel__toggle:hover {
  background: var(--primary-dark, #013610);
}

.file-panel__dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  margin-top: 0.5rem;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  min-width: 250px;
  max-height: 400px;
  overflow-y: auto;
  z-index: 10;
}

.file-panel__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem 1rem;
  border-bottom: 1px solid #eee;
}

.file-panel__header h3 {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
}

.file-panel__create-btn {
  background: none;
  border: none;
  cursor: pointer;
  color: var(--primary-color, #001f3f);
  padding: 0.25rem;
  display: flex;
  align-items: center;
  transition: transform 0.2s;
}

.file-panel__create-btn:hover {
  transform: scale(1.1);
}

.file-panel__list {
  padding: 0.5rem 0;
}

.file-panel__item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  cursor: pointer;
  transition: background 0.2s;
  color: #333;
}

.file-panel__item:hover {
  background: #f5f5f5;
}

.file-panel__item--active {
  background: #e8f5e9;
  color: var(--primary-color, #001f3f);
  font-weight: 600;
}

.file-panel__filename {
  flex: 1;
  font-size: 14px;
}

.file-panel__delete-btn {
  background: none;
  border: none;
  cursor: pointer;
  color: #d32f2f;
  padding: 0.25rem;
  display: flex;
  align-items: center;
  opacity: 0;
  transition: opacity 0.2s;
}

.file-panel__item:hover .file-panel__delete-btn {
  opacity: 1;
}

.file-panel__delete-btn:hover {
  color: #b71c1c;
}
</style>
