// frontend/src/shared/components/MonacoEditor.vue
<template>
  <div ref="editorContainer" class="monaco-editor-container"></div>
</template>

<script>
import { ref, onMounted, onUnmounted, watch } from 'vue';
import loader from '@monaco-editor/loader';

export default {
  name: 'MonacoEditor',
  props: {
    code: {
      type: String,
      default: ''
    },
    language: {
      type: String,
      default: 'python'
    }
  },
  emits: ['update:code', 'change'],
  setup(props, { emit, expose }) {
    const editorContainer = ref(null);
    let editor = null;
    let isUpdatingFromProp = false;

    onMounted(async () => {
      const monaco = await loader.init();

      if (!editorContainer.value) return;

      const isMobile = window.matchMedia('(max-width: 768px)').matches;

      editor = monaco.editor.create(editorContainer.value, {
        value: props.code,
        language: props.language,
        theme: 'vs-dark',
        automaticLayout: true,
        fontSize: isMobile ? 11 : 14,
        minimap: { enabled: !isMobile },
        scrollBeyondLastLine: false,
        wordWrap: 'on',
        tabSize: 4,
      });

      editor.onDidChangeModelContent(() => {
        if (!isUpdatingFromProp) {
          const value = editor.getValue();
          emit('update:code', value);
          emit('change', value);
        }
      });
    });

    watch(() => props.code, (newCode) => {
      if (editor && editor.getValue() !== newCode) {
        isUpdatingFromProp = true;
        editor.setValue(newCode || '');
        isUpdatingFromProp = false;
      }
    });

    onUnmounted(() => {
      if (editor) {
        editor.dispose();
      }
    });

    const undo = () => {
      if (editor) {
        editor.trigger('keyboard', 'undo', null);
      }
    };

    const redo = () => {
      if (editor) {
        editor.trigger('keyboard', 'redo', null);
      }
    };

    const getPosition = () => {
      if (editor) {
        return editor.getPosition();
      }
      return null;
    };

    const insertText = (text, position) => {
      if (editor) {
        const range = {
          startLineNumber: position.lineNumber,
          startColumn: position.column,
          endLineNumber: position.lineNumber,
          endColumn: position.column
        };
        editor.executeEdits('', [{
          range: range,
          text: text,
          forceMoveMarkers: true
        }]);
        editor.focus();
      }
    };

    expose({ undo, redo, getPosition, insertText });

    return {
      editorContainer,
    };
  }
};
</script>

<style scoped>
.monaco-editor-container {
  width: 100%;
  height: 100%;
  min-height: 400px;
}
</style>

// extra_files/frontend/src/components/MonacoEditor.tsx
import { Editor } from '@monaco-editor/react';
import { useTheme } from '../theme/ThemeProvider';
import { useRef, useImperativeHandle, forwardRef, useEffect } from 'react';

interface MonacoEditorProps {
  code: string;
  onChange: (value: string | undefined) => void;
  language?: string;
  readOnly?: boolean;
  height?: string;
}

export interface MonacoEditorRef {
  undo: () => void;
  redo: () => void;
  getValue: () => string | undefined;
}

const MonacoEditor = forwardRef<MonacoEditorRef, MonacoEditorProps>(({
  code,
  onChange,
  language = 'python',
  readOnly = false,
  height = '100%'
}, ref) => {
  const { theme } = useTheme();
  const editorRef = useRef<any>(null);
  const isUpdatingFromProps = useRef(false);

  useImperativeHandle(ref, () => ({
    undo: () => {
      editorRef.current?.trigger('keyboard', 'undo', null);
    },
    redo: () => {
      editorRef.current?.trigger('keyboard', 'redo', null);
    },
    getValue: () => {
      return editorRef.current?.getValue();
    }
  }));

  const handleEditorDidMount = (editor: any) => {
    editorRef.current = editor;
  };

  // Update editor content when code prop changes from outside
  useEffect(() => {
    if (editorRef.current && code !== editorRef.current.getValue()) {
      isUpdatingFromProps.current = true;
      const position = editorRef.current.getPosition();
      editorRef.current.setValue(code);
      if (position) {
        editorRef.current.setPosition(position);
      }
      isUpdatingFromProps.current = false;
    }
  }, [code]);

  const handleChange = (value: string | undefined) => {
    // Only call onChange if the change came from user interaction, not from props update
    if (!isUpdatingFromProps.current) {
      onChange(value);
    }
  };

  return (
    <Editor
      height={height}
      language={language}
      theme={theme === 'dark' ? 'vs-dark' : 'vs-light'}
      defaultValue={code}
      onChange={handleChange}
      onMount={handleEditorDidMount}
      options={{
        readOnly,
        minimap: { enabled: true },
        fontSize: 14,
        lineNumbers: 'on',
        scrollBeyondLastLine: false,
        automaticLayout: true,
        tabSize: 4,
        insertSpaces: true,
        wordWrap: 'on',
        formatOnPaste: true,
        formatOnType: true,
      }}
    />
  );
});

MonacoEditor.displayName = 'MonacoEditor';

export default MonacoEditor;
