// codespace-app/src/views/Login.vue
<template>
  <div class="auth-container">
    <div class="auth-card">
      <div class="auth-header">
        <h1 class="auth-logo">PyTalk</h1>
        <p class="auth-subtitle">Sign in to your account</p>
      </div>
      
      <form @submit.prevent="handleLogin" class="auth-form">
        <div class="form-group">
          <label for="email">Username</label>
          <input
            type="text"
            id="email"
            v-model="email"
            placeholder="Enter your username"
            required
            class="form-input"
          />
        </div>
        
        <div class="form-group">
          <label for="password">Password</label>
          <input 
            type="password" 
            id="password"
            v-model="password"
            placeholder="Enter your password"
            required
            class="form-input"
          />
        </div>
        
        <div class="form-options">
          <label class="checkbox-label">
            <input type="checkbox" v-model="rememberMe" />
            <span>Remember me</span>
          </label>
          <a href="#" class="forgot-link">Forgot password?</a>
        </div>
        
        <button type="submit" class="auth-button" :disabled="isLoading">
          {{ isLoading ? 'Signing In...' : 'Sign In' }}
        </button>
        
        <div class="auth-footer">
          <p>Don't have an account? <router-link to="/signup" class="auth-link">Sign up</router-link></p>
        </div>
      </form>
      
      <div v-if="error" class="error-message">{{ error }}</div>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuth } from '../composables/useAuth';
import axios from 'axios';
import { API_BASE_URL } from '../config/api';

export default {
  name: 'Login',
  setup() {
    const email = ref('');
    const password = ref('');
    const rememberMe = ref(false);
    const error = ref('');
    const isLoading = ref(false);
    const router = useRouter();
    const { login } = useAuth();

    const handleLogin = async () => {
      isLoading.value = true;
      error.value = '';

      try {
        const formData = new FormData();
        formData.append('username', email.value);
        formData.append('password', password.value);

        const res = await axios.post(`${API_BASE_URL}/api/v1/auth/login`, formData);

        login(res.data.user, res.data.access_token);
        router.push('/');
      } catch (err) {
        console.error('Login error:', err);
        error.value = err.response?.data?.detail || 'Login failed. Please check your credentials.';
      } finally {
        isLoading.value = false;
      }
    };

    return {
      email,
      password,
      rememberMe,
      error,
      isLoading,
      handleLogin,
    };
  }
};
</script>

<style scoped>
.auth-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #024A14 0%, #01350e 100%);
  padding: 20px;
}

.auth-card {
  background: white;
  border-radius: 16px;
  padding: 40px;
  width: 100%;
  max-width: 420px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
}

.auth-header {
  text-align: center;
  margin-bottom: 32px;
}

.auth-logo {
  font-family: 'Jaro', sans-serif;
  font-size: 36px;
  color: #024A14;
  margin-bottom: 8px;
}

.auth-subtitle {
  color: #666;
  font-size: 16px;
}

.auth-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.form-group label {
  font-size: 14px;
  font-weight: 500;
  color: #333;
}

.form-input {
  padding: 12px 16px;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  font-size: 14px;
  font-family: 'Jaldi', sans-serif;
  transition: all 0.2s ease;
}

.form-input:focus {
  outline: none;
  border-color: #024A14;
  box-shadow: 0 0 0 3px rgba(2, 74, 20, 0.1);
}

.form-options {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 14px;
}

.checkbox-label {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}

.checkbox-label input[type="checkbox"] {
  cursor: pointer;
}

.forgot-link {
  color: #024A14;
  text-decoration: none;
  font-weight: 500;
}

.forgot-link:hover {
  text-decoration: underline;
}

.auth-button {
  padding: 14px;
  background: #024A14;
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 16px;
  font-weight: 600;
  font-family: 'Jaldi', sans-serif;
  cursor: pointer;
  transition: all 0.2s ease;
  margin-top: 8px;
}

.auth-button:hover {
  background: #01350e;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(2, 74, 20, 0.3);
}

.auth-button:active {
  transform: translateY(0);
}

.auth-footer {
  text-align: center;
  margin-top: 24px;
  font-size: 14px;
  color: #666;
}

.auth-link {
  color: #024A14;
  text-decoration: none;
  font-weight: 600;
}

.auth-link:hover {
  text-decoration: underline;
}

.error-message {
  margin-top: 16px;
  padding: 12px;
  background: #fee;
  color: #c33;
  border-radius: 8px;
  font-size: 14px;
  text-align: center;
}
</style>

// frontend/src/pages/Login.tsx
import React, { type FormEvent, useState } from "react";
import { useNavigate } from "react-router-dom";
import "./styles/Login.css";

import api from "../services/api";
// import { API_BASE_URL } from "../config/api";
import { useAuth } from "../context/AuthContext";

export default function Login() {
    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState("");
    const navigate = useNavigate();

    const { login } = useAuth();

    async function onSubmit(e: FormEvent) {
        e.preventDefault();
        setIsLoading(true);
        setError("");

        try {
            const res = await api.post("/users/login", {
                username,
                password,
            });

            console.log("Login success:", res.data);

            // const userId = res.data.id;

            // const userRes = await api.get(`${API_BASE_URL}/users/${userId}`);
            // const userData = userRes.data;

            // Optionally store user info in localStorage or context
            // localStorage.setItem("user", JSON.stringify(userData));
            login(res.data);

            navigate("/homeReal");
        } catch (err: any) {
            console.error("Login error:", err);
            setError(
                err.response?.data?.detail ||
                "Login failed. Please check your credentials."
            );
        } finally {
            setIsLoading(false);
        }
    }

    return (
        <div className="login__viewport">
            {/* Logo (top-left) */}
            <div className="login__logo">PyTalk</div>

            {/* Center Card */}
            <div className="login__card" role="dialog" aria-labelledby="login-title">
                <h1 id="login-title" className="login__title">Log in</h1>

                <form className="login__form" onSubmit={onSubmit}>
                    <label className="login__field">
                        <input
                            type="text"
                            placeholder="USERNAME"
                            value={username}
                            onChange={(e) => setUsername(e.target.value)}
                            aria-label="Username"
                            required
                        />
                    </label>

                    <label className="login__field">
                        <input
                            type="password"
                            placeholder="PASSWORD"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            aria-label="Password"
                            required
                        />
                    </label>

                    {error && (
                        <div className="login__error" style={{ color: 'red', marginBottom: '1rem', fontSize: '0.9rem' }}>
                            {error}
                        </div>
                    )}

                    <p className="login__meta">
                        Don't have an account?{" "}
                        <a className="login__link" href="/pytalk/signup">Sign up</a>
                    </p>

                    <button type="submit" className="login__button" disabled={isLoading}>
                        {isLoading ? "LOGGING IN..." : "LOG IN"}
                    </button>
                </form>
            </div>
        </div>
    );
}
